labels:
  Deploy%20to%20Staging:
    environment: staging
    description: Staging deployment
    transient_environment: false
    required_contexts: ["Dummy"]
  Deploy%20to%20QA:
    environment: qa
    description: QA deployment
    transient_environment: false
    auto_merge: false
    required_contexts: []
