name: Build, Test and Publish

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, ubuntu-18.04, macOS-10.14]
        java: [ '1.7', '1.8', '1.9']

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test and Package      
      run: mvn package war:war
    - name: Save artifacts
      uses: actions/upload-artifact@master
      with:
        name: '${{matrix.os}}-${{matrix.java}}.WAR'
        path: .
