name: Build, Test and Publish

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    # The name below is the base of a required context for deployement. The generated value (i.e. `Build (ubuntu-18.04, 1.8)`) should match what's in `.github/deploy.yml` on `master` 
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, ubuntu-18.04, macOS-10.14]
        java: [ '1.7', '1.8', '1.9']

    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test and Package
      run: mvn package war:war
    - name: Save artifacts
      uses: actions/upload-artifact@master
      with:
        name: '${{matrix.os}}-${{matrix.java}}.WAR'
        path: .
    - name: Build the Docker image
      if: github.matrix.os == 'ubuntu-18.04'
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA
    - name: Publish to GitHub Package Registry
      if: github.matrix.os == 'ubuntu-18.04'
      env:
        DOCKER_TOKEN: ${{secrets.GPR_TOKEN}}
        DOCKER_USER: <token>
      run: |
        docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA
