name: Build Branch

on: [push]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: mvn test
    - name: Package
      run: mvn package war:war --file pom.xml -Dmaven.test.skip=true
    - name: Save builds artifacts
      uses: actions/upload-artifact@master
      with:
        name: ROOT.war
        path: /home/runner/work/azure-bookstore/azure-bookstore/target/ROOT.war