name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:

  clean:
    name: Cleanup Review apps
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the code
      uses: actions/checkout@v1
    - name: Delete deployments
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./.github/scripts/delete-deployments.sh
    - name: Login to Azure
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}

    - name: Delete the review apps
      env:
        RESOURCE_GROUP: bookstore
        GITHUB_HEAD_REF: ${{ format('refs/heads/{0}', github.head_ref) }}
      run: |
        az webapp list --resource-group $RESOURCE_GROUP --query "[?tags.ref=='$GITHUB_HEAD_REF'&&tags.type=='review']" > webapp-list.json
        filesize=$(wc -c < webapp-list.json); if [ "$filesize" -eq 3 ]; then exit 0; fi
        jq -j '.[].id+ " "' webapp-list.json
        WEBAPP_ID_LIST=$(jq -j '.[].id+" "' webapp-list.json) && az webapp delete --ids $WEBAPP_ID_LIST --keep-empty-plan
