name: Build, Test and Deploy

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: mvn test
    - name: Package
      run: mvn package war:war --file pom.xml -Dmaven.test.skip=true
    - name: Save builds artifacts
      uses: actions/upload-artifact@master
      with:
        name: ROOT.war
        path: /home/runner/work/azure-bookstore/azure-bookstore/target/ROOT.war

  login:
    name: Login to Azure
    runs-on: ubuntu-latest

    steps:
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Confirm active apps
      run: |
        az webapp list --query "[?state=='Running']"

  deploy:
    name: Deploy to AZ App Services
    needs: [build,login]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@master
      with:
        name: ROOT.war
        path: .
    - uses: azure/appservice-actions/webapp@master
      with:
        # Should be ${GITHUB_WORKPLACE/ROOT.WAR}
        package: /home/runner/work/azure-bookstore/azure-bookstore/ROOT.war
        app-name: githubookstore
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}