name: Build, Test and Deploy

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: mvn test
    - name: Build with Maven
      run: mvn package --file pom.xml
  login:
    name: Login to Azure
    runs-on: ubuntu-latest

    steps:
      - uses: azure/actions/login@master
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az webapp list --query "[?state=='Running']"
  deploy:
    name: Deploy to AZ App Services
    needs: [login,build]
    runs-on: ubuntu-latest

    steps:
    - uses: azure/appservice-actions/webapp@master
      with:
        app-name: githubookstore
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}