name: Build and Deploy a PR

on:
  deployment

jobs:

  login:
    name: Login to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Login
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}

  provision:
    name: Provision the Azure WebApp
    needs: login
    runs-on: ubuntu-latest

    steps:
    - name: Confirm active apps
      run: |
        az webapp list --query "[?state=='Running']"

  deploy:
    name: Deploy to AZ App Services
    needs: provision
    runs-on: ubuntu-latest

    steps:
    - uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'bookstore'
        images: docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA

  deployment-status:
    name: Update the deployment status
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set deployment status
      run: ./.github/scripts/udpate-deployment-status.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_URL: http://qa-githubookstore.azurewebsites.net/
