name: Deploy a review app on Azure

on:
  deployment

jobs:

  deploy:
    name: Deploy a review app on Azure
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}
    - name: Login to GitHub Package Registry
      uses: azure/container-actions/docker-login@master
      with:
        login-server: docker.pkg.github.com
        username: <token>
        password: ${{secrets.GPR_TOKEN}}
    - name: Create the review app
      env:
        RESOURCE_GROUP: bookstore
        APP_SERVICE_PLAN: bookstore-app-service-plan
        WEBAPP_NAME_PREFIX: bookstore-review
        DOCKER_USERNAME: <token>
        DOCKER_PASSWORD: ${{secrets.GPR_TOKEN}}
        DOCKER_REGISTRY_URL: docker.pkg.github.com
      run: |
        az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME_PREFIX-$GITHUB_SHA --output json > $HOME/azure_webapp_creation.json
        az webapp config container set --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME_PREFIX-$GITHUB_SHA --docker-registry-server-password $DOCKER_PASSWORD --docker-registry-server-user $DOCKER_USERNAME --docker-registry-server-url $DOCKER_REGISTRY_URL
    - name: Confirm active apps
      run: |
        az webapp list --query "[?state=='Running']"
    - name: Deploy
      uses: azure/appservice-actions/webapp-container@master
      env:
        WEBAPP_NAME_PREFIX: bookstore-review
      with:
        app-name: ${{ format('{0}-{1}', 'bookstore-review', github.sha) }}
        images: ${{ format('{0}/{1}/{2}:{3}', 'docker.pkg.github.com', github.repository, 'bookstore', github.sha) }}

  deployment-status:
    name: Update the deployment status
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set deployment status
      run: ./.github/scripts/udpate-deployment-status.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_URL: http://qa-githubookstore.azurewebsites.net/
