name: Build and Deploy a PR

on:
  deployment

jobs:

  deploy:
    name: Deploy a review app on Azure
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}
    - name: Login to GitHub Package Registry
      env:
        DOCKER_TOKEN: ${{secrets.GPR_TOKEN}}
        DOCKER_USER: <token>
      run: |
        docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Create the review app
      env:
        RESOURCE_GROUP: bookstore
        APP_SERVICE_PLAN: bookstore-app-service-plan
        WEBAPP_NAME_PREFIX: bookstore-review
      run: |
        az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME_PREFIX-${GITHUB_SHA:0:7} --deployment-container-image-name docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA --output json > $HOME/azure_webapp_creation.json
    - name: Confirm active apps
      run: |
        az webapp list --query "[?state=='Running']"
    - name: Deploy
      uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'bookstore'
        images: docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA

  deployment-status:
    name: Update the deployment status
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set deployment status
      run: ./.github/scripts/udpate-deployment-status.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_URL: http://qa-githubookstore.azurewebsites.net/
